version: 2
project_name: wiff

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc

brews:
  - repository:
      owner: h0rv
      name: homebrew-tap
    homepage: https://github.com/h0rv/wiff
    description: A terminal diff viewer with syntax highlighting, side-by-side mode, live updates, and hunk navigation
    license: MIT
    install: |
      bin.install "wiff"
    test: |
      system "#{bin}/wiff", "--version"
